# Generated by Django 5.2.7 on 2025-11-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_user_hotel_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='staff_whatsapp_group_code',
            field=models.CharField(blank=True, help_text='WhatsApp *group invite* link or code. Example link: https://chat.whatsapp.com/ABCDefghIjkLmNo You may also paste only the code: ABCDefghIjkLmNo', max_length=191),
        ),
    ]
