# Generated by Django 5.2.7 on 2025-11-20 14:15

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_hotel_staff_whatsapp_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='billing_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Billing amount per period (e.g. per month or per year).', max_digits=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='billing_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', help_text='Billing frequency for this hotel.', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='billing_start_date',
            field=models.DateField(blank=True, help_text='Date from which platform billing should be calculated.', null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='staff_whatsapp_group_code',
            field=models.CharField(blank=True, help_text='WhatsApp invite code for staff group (e.g. B78LUcPkZ520TSPRIIcFaV)', max_length=64),
        ),
        migrations.CreateModel(
            name='HotelPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='Payment date (when money was received).')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(choices=[('PG', 'Payment Gateway'), ('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('UPI', 'UPI'), ('OTHER', 'Other')], default='PG', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Transaction ID, bank ref, or any short note.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='website.hotel')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
