# Generated by Django 5.2.7 on 2025-11-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_hotel_billing_amount_hotel_billing_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpayment',
            name='gateway',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hotelpayment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
