# Generated by Django 5.2.7 on 2025-10-28 08:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelportal', '0007_request_service_item'),
        ('website', '0002_alter_user_hotel_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('number',)},
        ),
        migrations.AlterModelOptions(
            name='stay',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('BUSY', 'Busy'), ('CLEANING', 'Cleaning')], default='FREE', max_length=10),
        ),
        migrations.AddField(
            model_name='stay',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_stay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_current', to='hotelportal.stay'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotelportal.room'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CHECKED_OUT', 'Checked Out')], default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['hotel', 'status', 'created_at'], name='hotelportal_hotel_i_8a8f69_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['hotel', 'room', 'status'], name='hotelportal_hotel_i_e642ce_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['phone'], name='hotelportal_phone_3e37fe_idx'),
        ),
    ]
