# Generated by Django 5.2.7 on 2025-11-11 11:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelportal', '0008_alter_room_options_alter_stay_options_room_status_and_more'),
        ('website', '0002_alter_user_hotel_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_number', models.CharField(blank=True, max_length=32)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('next_invoice_seq', models.PositiveIntegerField(default=1)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_settings', to='website.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Billing Settings',
                'verbose_name_plural': 'Hotel Billing Settings',
            },
        ),
    ]
