# Generated by Django 5.2.7 on 2025-11-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelportal', '0010_stay_invoice_no_stay_is_paid_stay_paid_at_and_more'),
        ('website', '0002_alter_user_hotel_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('ROOM', 'Room Charge'), ('OTHER', 'Other')], default='', max_length=10),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['hotel', 'invoice_no'], name='hotelportal_hotel_i_3982af_idx'),
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_no__isnull', False)), fields=('hotel', 'invoice_no'), name='uniq_hotel_invoice_no'),
        ),
    ]
