# Generated by Django 5.2.7 on 2025-11-18 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelportal', '0011_alter_stay_payment_mode_and_more'),
        ('website', '0002_alter_user_hotel_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Internal code (e.g. accepted, rejected_evening).')),
                ('label', models.CharField(help_text="Shown in dropdown on Live Board (e.g. 'Accepted – Standard').", max_length=100)),
                ('type', models.CharField(choices=[('GENERIC', 'Generic / Manual'), ('ACCEPTED', 'Request Accepted'), ('REJECTED', 'Request Rejected / Cannot Serve'), ('COMPLETED', 'Request Completed'), ('CHECKIN', 'Welcome / Check-in'), ('CHECKOUT', 'Checkout / Goodbye')], default='GENERIC', max_length=20)),
                ('body', models.TextField(help_text='Template text with placeholders like {guest_name}, {room_number}, {hotel_name}, {tracking_url}, {request_id}.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='website.hotel')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'unique_together': {('hotel', 'code')},
            },
        ),
    ]
