# Generated by Django 5.2.7 on 2025-11-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelportal', '0012_whatsapptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Square icon for guest bottom category bar.', null=True, upload_to='category_icons/'),
        ),
    ]
