# Generated by Django 5.2.7 on 2025-11-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelportal', '0013_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
